<?php 
namespace Common\Model;
use Think\Model\ViewModel;
class AnliViewModel extends ViewModel {
	protected $viewFields=array(
        'document'=>array(
			'id'=>'did',  
			'uid'=>'uid',
			'name'=>'dname',
			'title'=>'dtitle',
			'keywords'=>'keywords',
			'description'=>'description',
			'category_id'=>'category_id',
			'group_id'=>'group_id',
			'root'=>'root',
			'pid'=>'pid',
			'model_id'=>'model_id',
			'type'=>'dtype',
			'position'=>'position',
			'link_id'=>'link_id',
			'cover_id'=>'cover_id',
			'view'=>'view',
			'comment'=>'comment',
			'extend'=>'extend',
			'level'=>'level',
			'status'=>'status',
			'create_time'=>'create_time', 
			'litpic'=>'litpic'
			),
		'document_anli'=>array(
			 'id', 
			    'aid',
			     'fengge',
			     'imgids',
			     'shejishi',
			     'loupan',
			     'mianji',
			     'jushi',
			     'zaojia',
			     'fangshi',
			     'zhucai',
			     'gongqi',
			    'home_pos',
			    'home_cover',
			    'home_sort',
			     'edate',
			     'rzloupan',
			    'detailpic',
			'_on'=>'document_anli.id=document.id',
			'_type'=>'LEFT',
			),
        'document_shejishi'=>array( 
			'nickname'=>'shejishiname',
			'_on'=>'document_anli.shejishi=document_shejishi.sno', 
			'_type'=>'LEFT',
			),
        'sys_enum_fengge'=>array( 
			'ename'=>'fenggename',
			'_on'=>'document_anli.fengge=sys_enum_fengge.evalue',
			'_type'=>'LEFT',
			),
        'sys_enum_jushi'=>array( 
			'ename'=>'jushiname',
			'_on'=>'document_anli.jushi=sys_enum_jushi.evalue',
			'_type'=>'LEFT',
			),
        'sys_enum_fangshi'=>array( 
			'ename'=>'fangshiname',
			'_on'=>'document_anli.fangshi=sys_enum_fangshi.evalue', 
			'_type'=>'LEFT',
			),
        'picture'=>array( 
			'path'=>'picpath',
			'_on'=>'document.cover_id=picture.id', 
			), 
	);
} 
?>